### ISSUE TITLE
Look at Gnome 40

### ISSUE THREAD

**Issue by jangernert** [elementary/streams#15]
- Install & test the latest builds of gnome 40
- General thoughts
- Compare how certain problems were solved compared to elemantary
  - Things elementary & gnome 40 are doing different and reasons for both approaches
  -  (educated guess in case of gnome 40)
- Were parts of gnome 40 inspired by elementary
- Does gnome 40 bring some new ideas that elementary wants to explore as well?

**Comment by cassidyjames** [comment]
Huh, that's really interesting actually, thanks for filing! This is something I kind of do privately anyway, so it could be interesting to capture it on a stream.
