### ISSUE TITLE
Hybrid graphics, Wine, Steam, Lutris setup

### ISSUE THREAD

**Issue by volfpeter** [elementary/streams#17]
How to get all these working correctly on top of a clean elementary install. Currently users need to look this up on stackexchange, reddit, etc.

**Comment by cassidyjames** [comment]
Hm… I think this might be a bit outside of the purpose of these streams, but it could be interesting for a community member to take on.

**Comment by danrabbit** [comment]
Yeah I agree this is probably out of scope. Our endorsed method for sideloading apps is from Flatpak. I don't think we really want to promote something like Wine. And hybrid graphics just needs work done to be supported. I don't think we want to encourage people to take on hacks and tweaks

**Comment by volfpeter** [comment]
Well, this is quite a basic thing, I can imagine plenty of people would be interested, so an "official" recommendation/guide would be nice, but of course I understand. Maybe the TheLinuxExperiment channel would be the best qualified to do this :)
BTW: any good content will be welcome!
